services:
  ircd:
    restart: on-failure:3
    build:
      context: .
    image: inspi4
    command: ${DAEMON_FLAGS}
    network_mode: "host"
    env_file: "config.env"
    volumes:
      - ./custom:/etc/inspircd/custom:ro
      - ./data:/var/lib/inspircd
      - ./log:/var/log/inspircd
