services:
  ircd:
    restart: on-failure:3
    build:
      context: .
    image: inspi4
    network_mode: "host"
    env_file: "config.env"
    volumes:
      - ./custom:/etc/inspircd/custom:ro
      - data:/var/lib/inspircd
      - log:/var/log/inspircd
volumes:
  data:
    name: inspi4_data
  log:
    name: inspi4_log
