services:
  tor:
    restart: on-failure:3
    build:
      context: .
    image: tor
    network_mode: "host"
    volumes:
      - data:/var/lib/inspircd
    ulimits:
      nofile:
        soft: "102400"
        hard: "102400"
    logging:
      driver: "json-file"
      options:
        max-size: "64k"
volumes:
  data:
    name: tor_data
